# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-30 06:54
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('housefinance', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='sys_user',
            field=models.OneToOneField(blank=True, default="", on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
